# Generated by Django 5.1.2 on 2024-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('Name', models.CharField(max_length=15)),
                ('Aadharno', models.IntegerField(primary_key='Aadharno', serialize=False)),
                ('address', models.CharField(max_length=20)),
                ('loanamt', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
